# Generated by Django 5.0 on 2023-12-28 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DicomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="dicom_images/")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor_dashboard.patient",
                    ),
                ),
            ],
        ),
    ]
