# Generated by Django 5.0 on 2023-12-21 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="file",
            field=models.FileField(default="medical_report.txt", upload_to="reports/"),
        ),
        migrations.AddField(
            model_name="report",
            name="title",
            field=models.CharField(default="Untitled Report", max_length=100),
        ),
        migrations.AddField(
            model_name="report",
            name="uploaded_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medapp_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
