# Generated by Django 5.0 on 2024-01-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imaging",
            name="image",
        ),
        migrations.AddField(
            model_name="imaging",
            name="image_or_zip",
            field=models.CharField(default="not_provided", max_length=255),
        ),
    ]
