# Generated by Django 5.0 on 2024-01-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medapp", "0002_remove_imaging_image_imaging_image_or_zip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imaging",
            name="image_or_zip",
            field=models.FileField(upload_to="images_or_zips/"),
        ),
    ]
