# Generated by Django 5.0 on 2024-01-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medapp", "0003_alter_imaging_image_or_zip"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="report_file",
            field=models.FileField(default="default_report.pdf", upload_to="reports/"),
        ),
    ]
