# Generated by Django 5.0 on 2024-01-08 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medapp", "0004_report_report_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="medapp.userprofile",
            ),
        ),
    ]
