# Generated by Django 5.0 on 2024-01-08 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medapp", "0006_userprofile_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="doctor",
            new_name="patient",
        ),
    ]
