# Generated by Django 5.0 on 2024-01-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medapp", "0007_rename_doctor_report_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="file",
            field=models.FileField(default="default_file.pdf", upload_to=""),
        ),
    ]
