# Generated by Django 5.0 on 2024-01-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medapp", "0008_report_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="report_file",
        ),
        migrations.AlterField(
            model_name="report",
            name="file",
            field=models.FileField(default="default_file.pdf", upload_to="reports/"),
        ),
    ]
